@echo off
echo Downloading FFmpeg...
curl -L -o ffmpeg.zip "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
echo Extracting FFmpeg...
powershell -command "Expand-Archive -Path ffmpeg.zip -DestinationPath temp_ffmpeg -Force"
echo Copying FFmpeg executable...
for /r temp_ffmpeg %%i in (ffmpeg.exe) do copy "%%i" ffmpeg.exe
echo Cleaning up...
del ffmpeg.zip
rmdir /s /q temp_ffmpeg
echo FFmpeg setup complete!
pause